/**
 * MoonData — loads and exposes real NASA lunar datasets.
 *
 * Data sources (NASA CGI Moon Kit, public domain):
 *   svs.gsfc.nasa.gov/4720
 *
 * Current setup (texture LOD):
 *   Level 0: lroc_color_4k.png (4096×2048) — far tiles
 *   Level 1: lroc_color_8k.png (8192×4096) — close tiles
 *
 * Elevation: ldem_16_uint.tif — LOLA 16ppd (5760×2880)
 *
 * Detail: regolith_detail.png (1024×1024) — procedural tileable modulation map
 *   Generated by scripts/generate-regolith.js.
 *   Greyscale, stored in linear space.  0.5 = neutral; < 0.5 = darken (crevice).
 */

import * as THREE from 'three';
import { fromArrayBuffer } from 'geotiff';

// ---------------------------------------------------------------------------
// Config — texture LOD levels
// ---------------------------------------------------------------------------

const TEXTURE_LOD = [
  { path: '/textures/lroc_color_4k.png',  size: 4096 },
  { path: '/textures/lroc_color_8k.png',  size: 8192 },
];

const TEXTURE_CONFIG = {
  elevation:       '/textures/ldem_16_uint.tif',
  regolithDetail:  '/textures/regolith_detail.png',
};

/**
 * LOLA uint16 encoding:
 *   stored value = elevation_in_half_metres + OFFSET
 *   elevation_m  = (value − OFFSET) × 0.5
 */
const LOLA_OFFSET_HM = 20_000;   // half-metres added to ensure all values > 0

export class MoonData {
  /**
   * @param {number} moonRadius  Game-space sphere radius (e.g. 1000)
   */
  constructor(moonRadius = 1000) {
    this.moonRadius = moonRadius;

    /** @type {THREE.Texture[]} */
    this.colorTextures = [];

    /**
     * Tileable regolith detail modulation map.
     * Greyscale 1024×1024.  Linear space.  0.5 = neutral.
     * @type {THREE.Texture|null}
     */
    this.detailTexture = null;

    // Elevation raster (typed array + dimensions)
    this._elev      = null;   // Uint16Array
    this._elevW     = 0;
    this._elevH     = 0;

    // Pre-computed scale: (game units per half-metre)
    // half-metre → km: × 0.0005
    // km → game units: × (moonRadius / 1737.4)
    this._elevScale = 0.0005 * (moonRadius / 1737.4);
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /** Load all datasets.  Await this before creating TerrainSystem. */
  async load(renderer = null) {
    const [colorTexs, elevData, detailTex] = await Promise.all([
      this._loadColorLOD(renderer),
      this._loadElevation(),
      this._loadDetailTexture(renderer),
    ]);

    this.colorTextures = colorTexs;
    this._elev         = elevData.raster;
    this._elevW        = elevData.width;
    this._elevH        = elevData.height;
    this.detailTexture = detailTex;

    console.log(
      `[MoonData] loaded: ${this.colorTextures.length} color LOD levels, ` +
      `elevation ${this._elevW}×${this._elevH}, detail texture`
    );
  }

  /**
   * Sample terrain elevation at a unit-sphere direction.
   * Uses bilinear interpolation between the four surrounding LOLA pixels.
   *
   * @param {number} nx  x-component of normalised sphere direction
   * @param {number} ny  y-component
   * @param {number} nz  z-component
   * @returns {number}  Height above the reference sphere in game units
   */
  getElevationAt(nx, ny, nz) {
    if (!this._elev) return 0;

    // Sphere direction → lat/lon
    const lat = Math.asin(Math.max(-1, Math.min(1, ny)));  // [-π/2, π/2]
    const lon = Math.atan2(nz, nx);                         // [-π,   π]

    // Equirectangular: top of image = north pole (lat = π/2)
    //   normX = (lon + π) / 2π   → [0, 1], left = 180°W
    //   normY = (π/2 − lat) / π  → [0, 1], top  = 90°N
    const normX = (lon + Math.PI) / (2 * Math.PI);
    const normY = (Math.PI / 2 - lat) / Math.PI;

    const px = normX * (this._elevW - 1);
    const py = normY * (this._elevH - 1);

    // Bilinear interpolation.
    // X wraps (longitude is periodic): x1 = (x0+1) % width ensures the sample
    // at the rightmost pixel (180°E) blends with the leftmost (180°W/0°) — the
    // same geographic location — making elevation and its gradient seamless.
    // Y clamps at poles (latitude is not periodic).
    const x0 = Math.floor(px),  y0 = Math.floor(py);
    const x1 = (x0 + 1) % this._elevW;
    const y1 = Math.min(y0 + 1, this._elevH - 1);
    const tx = px - x0,  ty = py - y0;

    const s = (x, y) => this._elev[y * this._elevW + x];

    const raw =
        s(x0, y0) * (1 - tx) * (1 - ty)
      + s(x1, y0) *      tx  * (1 - ty)
      + s(x0, y1) * (1 - tx) *      ty
      + s(x1, y1) *      tx  *      ty;

    // Convert: uint16 → half-metres above reference → game units
    return (raw - LOLA_OFFSET_HM) * this._elevScale;
  }

  // ---------------------------------------------------------------------------
  // Internal loaders
  // ---------------------------------------------------------------------------

  async _loadColorLOD(renderer) {
    const maxAnisotropy = renderer?.capabilities?.getMaxAnisotropy() ?? 1;
    const textures = [];

    for (const { path: texPath, size } of TEXTURE_LOD) {
      const tex = await new Promise((resolve, reject) => {
        const loader = new THREE.TextureLoader();
        loader.load(texPath, (tex) => {
          tex.colorSpace = THREE.SRGBColorSpace;
          tex.wrapS = THREE.RepeatWrapping;
          tex.wrapT = THREE.ClampToEdgeWrapping;
          tex.minFilter = THREE.LinearMipmapLinearFilter;
          tex.magFilter = THREE.LinearFilter;
          tex.anisotropy = Math.min(16, maxAnisotropy);
          tex.generateMipmaps = true;
          tex.needsUpdate = true;
          resolve(tex);
        }, undefined, reject);
      });
      textures.push(tex);
      console.log(`[MoonData] loaded ${size}x${size/2} color texture`);
    }

    return textures;
  }

  /**
   * Load the procedural regolith detail modulation texture.
   *
   * Stored in linear space (not sRGB) — RepeatWrapping so it tiles across
   * the surface at whatever scale the shader chooses.  High anisotropy for
   * crisp appearance at oblique viewing angles (first-person walking).
   */
  async _loadDetailTexture(renderer) {
    const maxAnisotropy = renderer?.capabilities?.getMaxAnisotropy() ?? 1;

    return new Promise((resolve, reject) => {
      const loader = new THREE.TextureLoader();
      loader.load(TEXTURE_CONFIG.regolithDetail, (tex) => {
        // Linear color space — this is a modulation map, not photographic color.
        tex.colorSpace   = THREE.LinearSRGBColorSpace;
        tex.wrapS        = THREE.RepeatWrapping;
        tex.wrapT        = THREE.RepeatWrapping;
        tex.minFilter    = THREE.LinearMipmapLinearFilter;
        tex.magFilter    = THREE.LinearFilter;
        tex.anisotropy   = Math.min(16, maxAnisotropy);
        tex.generateMipmaps = true;
        tex.needsUpdate  = true;
        resolve(tex);
      }, undefined, reject);
    });
  }

  async _loadElevation() {
    // Fetch the TIFF as a raw buffer, then parse with geotiff.js.
    // This avoids any browser TIFF support requirement.
    const response = await fetch(TEXTURE_CONFIG.elevation);
    if (!response.ok) {
      throw new Error(`Failed to fetch elevation data: HTTP ${response.status}`);
    }
    const buffer = await response.arrayBuffer();

    const tiff  = await fromArrayBuffer(buffer);
    const image = await tiff.getImage();
    const rasters = await image.readRasters();

    // readRasters() returns an array of band arrays.
    // For this single-band uint16 TIFF: rasters[0] is Uint16Array.
    const raster = rasters[0];
    const width  = image.getWidth();
    const height = image.getHeight();

    if (!(raster instanceof Uint16Array)) {
      console.warn('[MoonData] Elevation raster is not Uint16Array:', raster.constructor.name);
    }

    return { raster, width, height };
  }
}
